server:
  port: 8082

spring:
  application:
    name: Customer

  datasource:
    url: jdbc:mysql://localhost:3306/FoodioCustomer
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update